version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"  #this is used to forward the container port to your laptops port
    environment:
      MYSQL_DATABASE: mandanadb
      MYSQL_USER: mandana
      MYSQL_PASSWORD: mypassword
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  db: