spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/mandanadb
    username: mandana
    password: mypassword
    driverClassName: com.mysql.cj.jdbc.Driver

